# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `nilify_blanks` gem.
# Please instead update this file by running `bin/tapioca gem nilify_blanks`.


# pkg:gem/nilify_blanks#lib/nilify_blanks.rb:3
module NilifyBlanks
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::NilifyBlanks::ClassMethods

  # pkg:gem/nilify_blanks#lib/nilify_blanks.rb:66
  def nilify_blanks; end

  module GeneratedClassMethods
    def nilify_blanks_columns; end
    def nilify_blanks_columns=(value); end
    def nilify_blanks_columns?; end
    def nilify_blanks_options; end
    def nilify_blanks_options=(value); end
    def nilify_blanks_options?; end
  end

  module GeneratedInstanceMethods
    def nilify_blanks_columns; end
    def nilify_blanks_columns?; end
    def nilify_blanks_options; end
    def nilify_blanks_options?; end
  end
end

# pkg:gem/nilify_blanks#lib/nilify_blanks.rb:11
module NilifyBlanks::ClassMethods
  # This overrides the underlying rails method that defines attribute methods.
  # This must be thread safe, just like the underlying method.
  #
  # pkg:gem/nilify_blanks#lib/nilify_blanks.rb:20
  def define_attribute_methods; end

  # pkg:gem/nilify_blanks#lib/nilify_blanks.rb:26
  def nilify_blanks(options = T.unsafe(nil)); end

  private

  # pkg:gem/nilify_blanks#lib/nilify_blanks.rb:38
  def define_nilify_blank_methods; end
end

# pkg:gem/nilify_blanks#lib/nilify_blanks.rb:13
NilifyBlanks::ClassMethods::DEFAULT_CALLBACK = T.let(T.unsafe(nil), Symbol)

# pkg:gem/nilify_blanks#lib/nilify_blanks.rb:12
NilifyBlanks::ClassMethods::DEFAULT_TYPES = T.let(T.unsafe(nil), Array)

# pkg:gem/nilify_blanks#lib/nilify_blanks/railtie.rb:5
class NilifyBlanks::Railtie < ::Rails::Railtie
  class << self
    # pkg:gem/nilify_blanks#lib/nilify_blanks/railtie.rb:15
    def insert; end
  end
end
