# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `OpenAI::PromptGuard`.
# Please instead update this file by running `bin/tapioca dsl OpenAI::PromptGuard`.


class OpenAI::PromptGuard
  sig { returns(T::Boolean) }
  def allowed; end

  sig { returns(T::Boolean) }
  def allowed?; end

  sig { returns(Arguments) }
  def arg; end

  sig { returns(T.nilable(::String)) }
  def content_type; end

  sig { returns(T::Boolean) }
  def content_type?; end

  sig { returns(Outputs) }
  def output; end

  sig { returns(::String) }
  def path; end

  sig { returns(T::Boolean) }
  def path?; end

  sig { returns(::String) }
  def raw_body; end

  sig { returns(T::Boolean) }
  def raw_body?; end

  sig { returns(T.nilable(::String)) }
  def reason; end

  sig { returns(T::Boolean) }
  def reason?; end

  private

  sig { params(value: T::Boolean).returns(T::Boolean) }
  def allowed=(value); end

  sig { params(value: T.nilable(::String)).returns(T.nilable(::String)) }
  def content_type=(value); end

  sig { params(value: ::String).returns(::String) }
  def path=(value); end

  sig { params(value: ::String).returns(::String) }
  def raw_body=(value); end

  sig { params(value: T.nilable(::String)).returns(T.nilable(::String)) }
  def reason=(value); end

  class << self
    sig { params(path: ::String, raw_body: ::String, content_type: T.nilable(::String)).returns(T.attached_class) }
    def run(path:, raw_body:, content_type: nil); end

    sig { params(path: ::String, raw_body: ::String, content_type: T.nilable(::String)).returns(T.attached_class) }
    def run!(path:, raw_body:, content_type: nil); end

    sig do
      params(
        service_or_config: T.any(::Operandi::Base, T::Hash[T.any(::String, ::Symbol), T.untyped]),
        config: T::Hash[T.any(::String, ::Symbol), T.untyped]
      ).returns(T.self_type)
    end
    def with(service_or_config, config = {}); end
  end

  class Arguments < T::Struct
    prop :path, ::String
    prop :raw_body, ::String
    prop :content_type, T.nilable(::String), default: nil
  end

  class Outputs < T::Struct
    prop :allowed, T::Boolean
    prop :reason, T.nilable(::String), default: nil
  end
end
